"""Train all 20 models once and serialize their real-dataset weights.

The public Streamlit app loads the generated pretrained_weights.py and performs
inference only. It must never retrain models for visitors.
"""
import base64
import gzip
import io
import torch

from model_zoo import MODEL_SPECS, train_one

torch.set_num_threads(2)


def pack_state_dict(model):
    buf = io.BytesIO()
    torch.save(model.state_dict(), buf, _use_new_zipfile_serialization=False)
    return base64.b64encode(gzip.compress(buf.getvalue(), 9)).decode("ascii")


def main():
    weights = {}
    metrics = {}
    for model_id, name, _, _, task in MODEL_SPECS:
        print(f"training model {model_id}: {name} | {task}", flush=True)
        model, losses, metric = train_one(model_id, epochs=3, lr=1e-3)
        model.eval()
        weights[model_id] = pack_state_dict(model)
        metrics[model_id] = {
            "final_loss": float(losses[-1]),
            "metric": float(metric),
        }
        print(f"completed model {model_id}: loss={losses[-1]:.5f}, metric={metric:.4f}", flush=True)

    lines = [
        "# Auto-generated by build_pretrained.py. DO NOT EDIT.",
        "import base64, gzip, io, torch",
        f"MODEL_METRICS = {metrics!r}",
        f"MODEL_WEIGHTS = {weights!r}",
        "",
        "def load_state(model_id):",
        "    raw = gzip.decompress(base64.b64decode(MODEL_WEIGHTS[int(model_id)]))",
        "    return torch.load(io.BytesIO(raw), map_location='cpu', weights_only=True)",
        "",
    ]
    with open("pretrained_weights.py", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote pretrained_weights.py", flush=True)


if __name__ == "__main__":
    main()
