"""Build persistent pretrained weights for the public Streamlit app.
Trains once on real public datasets, serializes CPU weights as base64/gzip,
and writes pretrained_weights.py. The deployed app loads these weights; visitors do not retrain.
"""
import base64,io,gzip,torch
import torch.nn.functional as F
from sklearn.datasets import load_breast_cancer,load_digits,fetch_20newsgroups
from sklearn.preprocessing import StandardScaler
from model_zoo import MODEL_SPECS,SPEC_BY_ID

torch.set_num_threads(2)

def dataset(kind,n=256):
    if kind=='tabular':
        d=load_breast_cancer(); x=torch.tensor(StandardScaler().fit_transform(d.data),dtype=torch.float32)[:n,:20]; y=torch.tensor(d.target,dtype=torch.long)[:n]; return x,y
    if kind=='image':
        d=load_digits(); x=torch.tensor(d.images/16.0,dtype=torch.float32)[:n,None,:,:]; y=torch.tensor(d.target%2,dtype=torch.long)[:n]; return x,y
    if kind=='sequence':
        from real_datasets import har
        x,y,_,_=har(); return x[:n,:,:8],(y[:n]==0).long()
    if kind=='pairs':
        d=load_digits(); x=torch.tensor(d.images.reshape(-1,64)/16.0,dtype=torch.float32)[:n,:20]; y=torch.tensor(d.target%2,dtype=torch.long)[:n]; return torch.cat([x,x+0.02*torch.randn_like(x)],0),y
    if kind=='graph':
        from real_datasets import cora
        x,y,_=cora(); feats=x[:,:4]; xs=[];ys=[]
        for i in range(min(n,x.shape[0]-6)):
            idx=torch.arange(i,i+6); xs.append(feats[idx]); ys.append((y[idx].float().mean()>3).long())
        return torch.stack(xs),torch.stack(ys)
    if kind=='text':
        from real_datasets import text_sequences
        X,Y,_,_,_=text_sequences(); return X[:n].float().view(-1,4,8)/1024.0,(Y[:n]>=2).long()
    raise ValueError(kind)

def train_one(mid):
    _,_,cls,kind,_=SPEC_BY_ID[mid]; dk='text' if mid in (9,10,11,18) else kind; x,y=dataset(dk,256); torch.manual_seed(1000+mid); m=cls(); opt=torch.optim.Adam(m.parameters(),lr=2e-3); m.train()
    for _ in range(2):
        opt.zero_grad(); logits=m(x); target=y[:logits.size(0)]; loss=F.cross_entropy(logits,target); loss.backward(); opt.step()
    m.eval()
    with torch.no_grad(): logits=m(x); target=y[:logits.size(0)]; acc=float((logits.argmax(1)==target).float().mean())
    buf=io.BytesIO(); torch.save(m.state_dict(),buf,_use_new_zipfile_serialization=False); packed=base64.b64encode(gzip.compress(buf.getvalue(),9)).decode('ascii'); return packed,acc

def main():
    weights={}; metrics={}
    for mid,_,_,_,_ in MODEL_SPECS:
        print('training model',mid); weights[mid],metrics[mid]=train_one(mid)
    lines=['# Auto-generated by .github/workflows/build-pretrained.yml. DO NOT EDIT.','import base64,gzip,io,torch',f'MODEL_METRICS={metrics!r}',f'MODEL_WEIGHTS={weights!r}','', 'def load_state(model_id):','    raw=gzip.decompress(base64.b64decode(MODEL_WEIGHTS[int(model_id)]))','    return torch.load(io.BytesIO(raw),map_location="cpu",weights_only=True)','']
    open('pretrained_weights.py','w',encoding='utf-8').write('\n'.join(lines)); print('wrote pretrained_weights.py')

if __name__=='__main__': main()
