"""Train all 20 models once and serialize their real-dataset weights.
The public Streamlit app loads pretrained_weights.py and performs inference only.
"""
import base64
import gzip
import io
import torch
import torch.nn.functional as F

from model_zoo import MODEL_SPECS, train_one, SPEC_BY_ID
from real_datasets import cora

torch.set_num_threads(2)


def pack_state_dict(model):
    buf = io.BytesIO()
    torch.save(model.state_dict(), buf, _use_new_zipfile_serialization=False)
    return base64.b64encode(gzip.compress(buf.getvalue(), 9)).decode("ascii")


def train_gnn_cpu(epochs=3, lr=1e-3):
    """Train GNN on a real 256-node Cora subgraph to keep free CI CPU-safe."""
    _, _, cls, _, _ = SPEC_BY_ID[20]
    x, y, a = cora()
    n = min(256, x.shape[0])
    x, y, a = x[:n], y[:n], a[:n, :n]
    model = cls()
    opt = torch.optim.Adam(model.parameters(), lr=lr)
    losses = []
    for _ in range(epochs):
        opt.zero_grad()
        loss = F.cross_entropy(model(x, a), y)
        loss.backward()
        opt.step()
        losses.append(float(loss))
    with torch.no_grad():
        metric = float((model(x, a).argmax(1) == y).float().mean())
    return model, losses, metric


def main():
    weights = {}
    metrics = {}
    for model_id, name, _, _, task in MODEL_SPECS:
        print(f"training model {model_id}: {name} | {task}", flush=True)
        if model_id == 20:
            model, losses, metric = train_gnn_cpu()
        else:
            model, losses, metric = train_one(model_id, epochs=3, lr=1e-3)
        model.eval()
        weights[model_id] = pack_state_dict(model)
        metrics[model_id] = {"final_loss": float(losses[-1]), "metric": float(metric)}
        print(f"completed model {model_id}: loss={losses[-1]:.5f}, metric={metric:.4f}", flush=True)

    lines = [
        "# Auto-generated by build_pretrained.py. DO NOT EDIT.",
        "import base64, gzip, io, torch",
        f"MODEL_METRICS = {metrics!r}",
        f"MODEL_WEIGHTS = {weights!r}",
        "",
        "def load_state(model_id):",
        "    raw = gzip.decompress(base64.b64decode(MODEL_WEIGHTS[int(model_id)]))",
        "    return torch.load(io.BytesIO(raw), map_location='cpu', weights_only=True)",
        "",
    ]
    with open("pretrained_weights.py", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote pretrained_weights.py", flush=True)


if __name__ == "__main__":
    main()
